# ---------------------------------------------------------------------------
# S3 — uploads bucket configuration (this backend region)
# The bucket is created manually. Terraform manages CORS, lifecycle, and IAM
# only, referencing the bucket via var.uploads_bucket_name.
# ---------------------------------------------------------------------------

resource "aws_s3_bucket_cors_configuration" "uploads" {
  bucket = var.uploads_bucket_name

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["PUT", "GET"]
    # Restrict to the app's public CloudFront FQDN — prevents other origins
    # from uploading directly via pre-signed URLs generated by this API.
    # var.cookie_domain is the full CloudFront subdomain (e.g. buddy-dev.example.com),
    # which matches the Origin header sent by the browser during PUT uploads.
    allowed_origins = ["https://${var.cookie_domain}"]
    expose_headers  = ["ETag"]
    max_age_seconds = 3600
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "uploads" {
  bucket = var.uploads_bucket_name

  rule {
    id     = "abort-incomplete-multipart"
    status = "Enabled"
    filter {}

    # Orphaned multipart uploads accumulate storage costs indefinitely.
    # 7 days is enough for any legitimate large upload to complete.
    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }

  rule {
    id     = "intelligent-tiering"
    status = "Enabled"
    filter {}

    # Move infrequently-accessed objects to Intelligent-Tiering after 90 days
    # to reduce storage costs without changing retrieval behaviour.
    transition {
      days          = 90
      storage_class = "INTELLIGENT_TIERING"
    }
  }
}

# ---------------------------------------------------------------------------
# ELB access-log delivery accounts — AWS assigns a distinct, fixed AWS-owned
# account per region for this purpose (published in AWS's ELB access-logging
# docs; these are not secrets — every AWS customer's ALB in that region uses
# the same account). Looked up by var.aws_region below rather than hardcoded
# to one region, since this module is applied once per region.
# ---------------------------------------------------------------------------
locals {
  elb_log_delivery_account_ids = {
    "ap-south-1" = "718504428378"
    "eu-west-1"  = "156460612806"
    "us-east-1"  = "127311923021"
  }
}

# ---------------------------------------------------------------------------
# S3 — regional logging bucket policy (this backend region)
# The bucket is created manually. Terraform manages the policy only.
# Created whenever EITHER enable_cloudtrail or enable_alb_access_logs is
# true — the two features are independent (see their own variable
# descriptions) but share this one bucket/policy resource, so either one
# needing write access is reason enough for the policy to exist. On dev/sbx,
# both flags default to false, so the policy doesn't exist there either.
#
# Two principals are granted write access:
#   1. ELB service account (region-specific, see local.elb_log_delivery_account_ids
#      above) — ALB access log delivery for this backend region. Only
#      actually used when enable_alb_access_logs = true (see alb.tf).
#   2. cloudtrail.amazonaws.com — requires GetBucketAcl to validate the
#      bucket exists and PutObject to write log files. Only actually used
#      when enable_cloudtrail = true.
# ---------------------------------------------------------------------------

resource "aws_s3_bucket_policy" "regional_logging" {
  count  = (var.enable_cloudtrail || var.enable_alb_access_logs) ? 1 : 0
  bucket = var.regional_logging_bucket_name

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "ALBAccessLogs"
        Effect = "Allow"
        Principal = {
          AWS = "arn:aws:iam::${local.elb_log_delivery_account_ids[var.aws_region]}:root"
        }
        Action   = "s3:PutObject"
        Resource = "arn:aws:s3:::${var.regional_logging_bucket_name}/alb-logs/*"
      },
      {
        Sid    = "CloudTrailAclCheck"
        Effect = "Allow"
        Principal = {
          Service = "cloudtrail.amazonaws.com"
        }
        Action   = "s3:GetBucketAcl"
        Resource = "arn:aws:s3:::${var.regional_logging_bucket_name}"
      },
      {
        Sid    = "CloudTrailWrite"
        Effect = "Allow"
        Principal = {
          Service = "cloudtrail.amazonaws.com"
        }
        Action   = "s3:PutObject"
        Resource = "arn:aws:s3:::${var.regional_logging_bucket_name}/cloudtrail/*"
        Condition = {
          StringEquals = {
            "s3:x-amz-acl" = "bucket-owner-full-control"
          }
        }
      }
    ]
  })
}
