# ---------------------------------------------------------------------------
# S3 — uploads bucket configuration (ap-south-1)
# The bucket is created manually. Terraform manages CORS, lifecycle, and IAM
# only, referencing the bucket via var.uploads_bucket_name.
# ---------------------------------------------------------------------------

resource "aws_s3_bucket_cors_configuration" "uploads" {
  bucket = var.uploads_bucket_name

  cors_rule {
    allowed_headers = ["*"]
    allowed_methods = ["PUT"]
    # Restrict to the app's public CloudFront FQDN — prevents other origins
    # from uploading directly via pre-signed URLs generated by this API.
    # var.cookie_domain is the full CloudFront subdomain (e.g. buddy-dev.example.com),
    # which matches the Origin header sent by the browser during PUT uploads.
    allowed_origins = ["https://${var.cookie_domain}"]
    expose_headers  = ["ETag"]
    max_age_seconds = 3600
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "uploads" {
  bucket = var.uploads_bucket_name

  rule {
    id     = "abort-incomplete-multipart"
    status = "Enabled"
    filter {}

    # Orphaned multipart uploads accumulate storage costs indefinitely.
    # 7 days is enough for any legitimate large upload to complete.
    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }

  rule {
    id     = "intelligent-tiering"
    status = "Enabled"
    filter {}

    # Move infrequently-accessed objects to Intelligent-Tiering after 90 days
    # to reduce storage costs without changing retrieval behaviour.
    transition {
      days          = 90
      storage_class = "INTELLIGENT_TIERING"
    }
  }
}

# ---------------------------------------------------------------------------
# S3 — regional logging bucket policy (ap-south-1)
# The bucket is created manually. Terraform manages the policy only.
# Skipped when var.enable_cloudtrail = false (dev/sbx).
#
# Two principals are granted write access:
#   1. ELB service account (718504428378) — ALB access logs for ap-south-1.
#      Account ID 718504428378 is the canonical ELB delivery account for
#      ap-south-1; newer accounts may also accept the service principal
#      logdelivery.elasticloadbalancing.amazonaws.com but the account ID
#      form is always safe and backwards compatible.
#   2. cloudtrail.amazonaws.com — requires GetBucketAcl to validate the
#      bucket exists and PutObject to write log files.
# ---------------------------------------------------------------------------

resource "aws_s3_bucket_policy" "regional_logging" {
  count  = var.enable_cloudtrail ? 1 : 0
  bucket = var.regional_logging_bucket_name

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid    = "ALBAccessLogs"
        Effect = "Allow"
        Principal = {
          AWS = "arn:aws:iam::718504428378:root"
        }
        Action   = "s3:PutObject"
        Resource = "arn:aws:s3:::${var.regional_logging_bucket_name}/alb-logs/*"
      },
      {
        Sid    = "CloudTrailAclCheck"
        Effect = "Allow"
        Principal = {
          Service = "cloudtrail.amazonaws.com"
        }
        Action   = "s3:GetBucketAcl"
        Resource = "arn:aws:s3:::${var.regional_logging_bucket_name}"
      },
      {
        Sid    = "CloudTrailWrite"
        Effect = "Allow"
        Principal = {
          Service = "cloudtrail.amazonaws.com"
        }
        Action   = "s3:PutObject"
        Resource = "arn:aws:s3:::${var.regional_logging_bucket_name}/cloudtrail/*"
        Condition = {
          StringEquals = {
            "s3:x-amz-acl" = "bucket-owner-full-control"
          }
        }
      }
    ]
  })
}
